ArtsInChicago/ArtsInChicago/Models/ArtworksList.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtsInChicago.Models
{
    public class ArtworksList
    {
        [JsonProperty("pagination")]
        public Pagination PagingParams { get; set; }

        [JsonProperty("data")]
        public List<Artwork> Data { get; set; }

        [JsonProperty("config")]
        public ArticConfig ArticConfig { get; set; }
    }
}

ArtsInChicago/ArtsInChicago/Models/ViewModels/ArtworksListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtsInChicago.Models.ViewModels
{
    public class ArtworksListViewModel
    {
        public ArtworksList ArtworksList { get; set; }

        public IEnumerable<string> ArtworkTypes { get; set; }
    }
}

ArtsInChicago/ArtsInChicago/Controllers/ArtworkDetailsController.cs
using ArtsInChicago.Models;
using ArtsInChicago.Models.ViewModels;
using ArtsInChicago.Services.Cotracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtsInChicago.Controllers
{
    public class ArtworkDetailsController : Controller
    {
        private readonly IArticService articService;

        public ArtworkDetailsController(IArticService articService)
        {
            this.articService = articService;
        }

        public async Task<IActionResult> Index(int id, string backController)
        {
            try
            {
                var artwork = await this.articService.GetArtworkByIdAsync(id);

                //return View(artwork);
                return View(new DetailsViewModel() { BackController = backController, Details = artwork });

            }
            catch(ArgumentNullException ex)
            {
                return NotFound(ex.Message);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

    }
}

ArtsInChicago/ArtsInChicago/Controllers/ArtworksListController.cs
using ArtsInChicago.Helpers;
using ArtsInChicago.Models;
using ArtsInChicago.Models.ViewModels;
using ArtsInChicago.Services.Contracts;
using ArtsInChicago.Services.Cotracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtsInChicago.Controllers
{
    public class ArtworksListController : Controller
    {
        private const string PAGE = "currentListPage";
        private const string PAGE_NUMBER = "listPageNumber";

        private readonly IArticService articService;
        private readonly IArtworkTypesService artworkTypesService;
        private readonly IMemoryCache memoryCache;

        public ArtworksListController(IArticService articService, IArtworkTypesService artworkTypesService, IMemoryCache memoryCache)
        {
            this.articService = articService;
            this.artworkTypesService = artworkTypesService;
            this.memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index(int? pageNumber, string artwork_type)
        {
            try
            {
                var typesCount = await this.artworkTypesService.GetCountAsync();
                var typesCollection = await this.artworkTypesService.GetAllAsync(typesCount);

                var artworksList = await this.articService.GetArtworksAsync(pageNumber, null, artwork_type);

                CachHelper.CachInMemory(artworksList, PAGE, this.memoryCache);
                CachHelper.CachInMemory(artworksList.PagingParams.CurrentPage, PAGE_NUMBER, this.memoryCache, 60);

                var viewModel = new ArtworksListViewModel();
                viewModel.ArtworksList = artworksList;
                viewModel.ArtworkTypes = typesCollection;

                return View(viewModel);

            }
            catch (Exception)
            {

                return RedirectToAction("Error", "Home");
            }        
        }

        public IActionResult IndexCached()
        {
            var cacheOutput = CachHelper.GetCachedInMemory<ArtworksList>(this.memoryCache, PAGE, PAGE_NUMBER);

            if (cacheOutput.obj != null)
            {
                return View("Index", cacheOutput.obj);
            }
            else
            {
                return RedirectToAction("Index", routeValues: new { pageNumber = cacheOutput.pageNumber });
            }
        }

    }
}

ArtsInChicago/ArtsInChicago/Controllers/GalleryController.cs
using ArtsInChicago.Helpers;
using ArtsInChicago.Models;
using ArtsInChicago.Services.Cotracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.IO;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;

namespace ArtsInChicago.Controllers
{
    public class GalleryController : Controller
    {
        private const string PAGE = "currentGalleryPage";
        private const string PAGE_NUMBER = "galleryPageNumber";

        private readonly IArticService articService;
        private readonly IMemoryCache memoryCache;

        public GalleryController(IArticService articService, IMemoryCache memoryCache)
        {
            this.articService = articService;
            this.memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            try
            {
                //var artworksList = await this.articService.GetArtworksAsync(pageNumber);
                var artworksList = await this.articService.GetArtworksAsync(pageNumber, null, null);

                CachHelper.CachInMemory(artworksList, PAGE, this.memoryCache);
                CachHelper.CachInMemory(artworksList.PagingParams.CurrentPage, PAGE_NUMBER, this.memoryCache, 60);

                return View(artworksList);

            }
            catch (Exception)
            {

                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult IndexCached()
        {
            var cacheOutput = CachHelper.GetCachedInMemory<ArtworksList>(this.memoryCache, PAGE, PAGE_NUMBER);

            if (cacheOutput.obj!=null)
            {
                return View("Index", cacheOutput.obj);
            }
            else
            {
                return RedirectToAction("Index", routeValues: new { pageNumber = cacheOutput.pageNumber });
            }
        }
    }
}

ArtsInChicago/ArtsInChicago/Views/ArtworksList/Index.cshtml
@model ArtsInChicago.Models.ViewModels.ArtworksListViewModel;

@{
    ViewData["Title:"] = "Artworks list";
}

<h4>List of current artworks ...</h4>

<form asp-controller="ArtworksList" asp-action="Index">
    <label>Select artwork type:</label>
    <select name="artwork_type" onchange="this.form.submit()">
        @foreach (var item in Model.ArtworkTypes)
        {
            <option>@item</option>
        }
    </select>
    <input type="submit" value="Filter" />
</form>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>Date</th>
            <th>Place of origin</th>
            <th>Department</th>
            <th>Ref. Number</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ArtworksList.Data)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Artist)</td>
                <td>@Html.DisplayFor(modelItem => item.Date)</td>
                <td>@Html.DisplayFor(modelItem => item.PlaceOfOrigin)</td>
                <td>@Html.DisplayFor(modelItem => item.Department)</td>
                <td>@Html.DisplayFor(modelItem => item.RefNumber)</td>
                <td>
                    @*<a asp-controller="ArtworkDetails" asp-action="Index" asp-route-id="@item.Id">Details</a>*@

                    @{
                        var parms = new Dictionary<string, string>
                            {
                                { "id", @item.Id.ToString() },
                                { "backController", "ArtworksList" }
                            };
                    }
                    <a asp-controller="ArtworkDetails" asp-action="Index" asp-all-route-data="parms">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    @{
        var prevDisabled = Model.ArtworksList.PagingParams.CurrentPage == 1 ? "disabled" : "";
        var nextDisabled = Model.ArtworksList.PagingParams.CurrentPage == Model.ArtworksList.PagingParams.TotalPages ? "disabled" : "";

    }

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item @prevDisabled"><a class="page-link" asp-controller="ArtworksList" asp-action="Index" asp-route-pageNumber="@(Model.ArtworksList.PagingParams.CurrentPage-1)">Previous</a></li>
            <li class="page-item"><a class="page-link" asp-controller="ArtworksList" asp-action="Index" asp-route-pageNumber="@Model.ArtworksList.PagingParams.CurrentPage">@Model.ArtworksList.PagingParams.CurrentPage</a></li>
            <li class="page-item @nextDisabled"><a class="page-link" asp-controller="ArtworksList" asp-action="Index" asp-route-pageNumber="@(Model.ArtworksList.PagingParams.CurrentPage+1)">Next</a></li>
        </ul>
    </nav>
</div>

<hr />
<div>
    <p>
        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        |
        <a asp-area="" asp-controller="Gallery" asp-action="Index">Gallery</a>
    </p>
</div>