ArtsInChicago/ArtsInChicago/Models/ArtworkDetails.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtsInChicago.Models
{
    public class ArtworkDetails
    {
        [JsonProperty("data")]
        public ArtworkDataFull Data { get; set; }

        [JsonProperty("config")]
        public ArticConfig ArticConfig { get; set; }

    }
}

ArtsInChicago/ArtsInChicago/Controllers/ArtworkDetailsController.cs
using ArtsInChicago.Models;
using ArtsInChicago.Models.ViewModels;
using ArtsInChicago.Services.Cotracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtsInChicago.Controllers
{
    public class ArtworkDetailsController : Controller
    {
        private readonly IArticService articService;

        public ArtworkDetailsController(IArticService articService)
        {
            this.articService = articService;
        }

        public async Task<IActionResult> Index(int id, string backController)
        {
            try
            {
                var artwork = await this.articService.GetArtworkByIdAsync(id);

                //return View(artwork);
                return View(new DetailsViewModel() { BackController = backController, Details = artwork });

            }
            catch(ArgumentNullException ex)
            {
                return NotFound(ex.Message);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

    }
}

ArtsInChicago/ArtsInChicago/Controllers/PrintToPdfController.cs
using ArtsInChicago.Helpers;
using ArtsInChicago.Models;
using ArtsInChicago.Services.Cotracts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ArtsInChicago.Controllers
{
    public class PrintToPdfController : Controller
    {
        private readonly IPdfPrintService pdfPrinter;
        private readonly IWebHostEnvironment environment;

        public PrintToPdfController(IPdfPrintService pdfPrinter, IWebHostEnvironment environment)
        {
            this.pdfPrinter = pdfPrinter;
            this.environment = environment;
        }

        [HttpPost]
        public async Task<IActionResult> Print([FromBody] ArtworkDataFull model)
        {

            string imageString = await PdfPrintHelper.GetImageBase64String(model.ImageUrl, this.environment);

            string fileName = this.pdfPrinter.PrintIndividualArtwork(model, imageString);
            this.pdfPrinter.OpenDoc(fileName);

            return StatusCode(200);
        }

        public class Model
        {
            public string Artist { get; set; }
        }
    }
}

ArtsInChicago/ArtsInChicago/Views/ArtworkDetails/Index.cshtml
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#printPDF").click(function () {
                var outputModel = {
                    ImageUrl: $('img').attr('src'),
                    Title: $('#m_title').text(),
                    Date: $('#m_date').text(),
                    Artist: $('#m_artist').text(),
                    PlaceOfOrigin: $('#place-of-origin').text(),
                    Medium: $('#m_medium').text(),
                    Dimentions: $('#m_dimentions').text(),
                    Description: $('#m_description').text()

                };

                $.ajax({
                    url: '@Url.Action("Print", "PrintToPdf")',
                    type: 'POST',
                    contentType: "application/json; charset=utf-8",
                    dataType:"json",
                    data: JSON.stringify(outputModel)
                });
            });
        });
    </script>
</head>

<body>
    @model ArtsInChicago.Models.ViewModels.DetailsViewModel;

    @{
        ViewData["Details"] = "Artwork details";
    }

    <div id="details">
        <img id="m_imageurl" src="@Model.Details.Data.ImageUrl" />
        <h2> <span id="m_title">@Model.Details.Data.Title </span>, <span id="m_date">@Model.Details.Data.Date</span></h2>
        <h4 id="m_artist">@Model.Details.Data.Artist</h4>
        <b>Place of origin:</b>
        <p id="place-of-origin">@Model.Details.Data.PlaceOfOrigin</p>
        <b>Medium:</b>
        <p id="m_medium">@Model.Details.Data.Medium</p>
        <b>Dimentions:</b>
        <p id="m_dimentions">@Model.Details.Data.Dimentions</p>
        <b>Description:</b>
        <p id="m_description">@Model.Details.Data.Description</p>

    </div>

    <hr />
    <div>
        <p>
            @{
                string text = "";
                switch (Model.BackController)
                {
                    case "ArtworksList": text = "list"; break;
                    case "Gallery": text = "gallery"; break;
                }
            }
            <a asp-area="" asp-controller="@Model.BackController" asp-action="IndexCached">Back to @text</a>
        </p>

    </div>

    <button id="printPDF" type="button" class="btn btn-outline-dark">Print to PDF</button>

</body>